### ISSUE TITLE
Urgent: Getting 500 response code when attempting to call sendTransacEmail

### ISSUE THREAD

**Issue by speriosu** [getbrevo/brevo-node#11]
I'm getting the same error the original posted reported here: https://github.com/sendinblue/APIv3-php-library/issues/68

This has been happening off and on since about 8am Pacific this morning.

Nothing has changed on our end, and our emails to customers are suddenly failing because of this.

Out code for interfacing with SIB/Brevo pretty much follows the Getting Started section here: https://www.npmjs.com/package/@getbrevo/brevo#getting-started

We know it's not an authentication issue, because if I intentionally put a mistake in our apiKey, I get a 401 (Unauthorized) rather than a 500 (Internal Server Error).

On our end, it actually makes no difference whether we use the new Brevo Node SDK or the previous SendInBlue V3 one. The behavior is the same in both cases.

Any help on this??

EDIT: Got a response to my support ticket on the Brevo dashboard, and they rep confirmed they're having internal issues and working on it.

**Comment by saurabh-antcreatives** [comment]
Fuck this service, very sad to see these kind of business these days.

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @speriosu 
I know it's late, but if you want SLA based support from Brevo please create a support ticket here: https://help.brevo.com/hc/en-us/articles/360020434360-Contact-the-support-team.

It could have been an intermittent issue but raising it there will fetch you accurate and timely response. Also, for the 401 it could be due to number of reasons. More details can be shared in support ticket only.
