### ISSUE TITLE
Dependance on vulnerable version of request

### ISSUE THREAD

**Issue by aliciagyt** [getbrevo/brevo-node#16]
I currently use version` 2.0.0-beta.4` and when I run `npm audit fix`, it signals me that I have 2 moderate vulnerabilities, one on `request` and one on `tough-cookie`, and that fixing them will install `brevo@1.0.1` because `brevo  >=2.0.0-beta.2` depends on vulnerable versions of `request`.
`request` being deprecated anyway ([source](https://github.com/request/request/issues/3142)), do you plan to switch to axios or another library soon? Thanks !

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @aliciagyt 
Here is a new version https://www.npmjs.com/package/@getbrevo/brevo/v/2.1.1 which has many critical and high security vulnerabilites issues fixed. Kindly check this out.
Thanks.

**Comment by milo-stadion** [comment]
@shubhamUpadhyayInBlue I've just updated to 2.1.1 and it still contains the vulnerable version of the request package. 

This package has been deprecated since 2020, so you should be looking to move to something new as a priority.

You can see more information about the deprecation [here](https://github.com/request/request)

You can find information about the vulnerability [here](https://github.com/advisories/GHSA-p8p7-x288-28g6)

![CleanShot 2024-05-01 at 09 28 11@2x](https://github.com/getbrevo/brevo-node/assets/148950277/ef95d22a-28ea-4f82-85e9-d34b67b4e399)

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @milo-stadion 
Yes I agree with you that request module should not be used since it's deprecated. But, since these SDKs are generated using the Openapi generator it's not very straight forward to stop the usage of existing dependency package and keep the SDK backward compatible for all the APIs we support. 


However, we will discuss it to come out with a solution to this problem soon.

Thanks.

**Comment by milo-stadion** [comment]
Thanks @shubhamUpadhyayInBlue
